version: "2"
services:

    kibana:
        image: "docker.elastic.co/kibana/kibana:7.13.4"
        container_name: kibana
        mem_reservation: 4G
        ports: 
            - 5601:5601
        environment: 
            - xpack.security.enabled=true
            - ELASTICSEARCH_USERNAME=elastic
            - ELASTICSEARCH_PASSWORD=default
            - ELASTICSEARCH_HOST=http://elasticsearch:9200
        networks: 
            - es-net
        depends_on: 
            - elasticsearch
    
    elasticsearch:
        image: "docker.elastic.co/elasticsearch/elasticsearch:7.13.4"
        ports:
            - 9200:9200
        container_name: elasticsearch
        restart: unless-stopped
        environment:
            - xpack.security.enabled=true
            - cluster.name=elasticsearch
            - node.name="db-master"
            - node.master=true
            - node.data=true
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
            - discovery.type=single-node
            - "ELASTIC_PASSWORD=default"
        volumes: 
            - es-data:/usr/share/elasticsearch/data
        networks: 
            - es-net
volumes:
    es-data:
        driver: local

networks:
    es-net: